import type { CanvasState, EntityId } from "./model";

export type GeneratedAssetDisplaySize = {
  width: number;
  height: number;
};

const DEFAULT_ASSET_SIZE: GeneratedAssetDisplaySize = { width: 640, height: 360 };
const MAX_FALLBACK_WIDTH = 640;
const MAX_FALLBACK_HEIGHT = 420;
const MIN_WIDTH = 80;
const MIN_HEIGHT = 60;

const fitWithin = (width: number, height: number, aspectRatio: number): GeneratedAssetDisplaySize => {
  const fittedWidth = Math.min(width, height * aspectRatio);
  const fittedHeight = fittedWidth / aspectRatio;
  return {
    width: Math.max(MIN_WIDTH, Math.round(fittedWidth)),
    height: Math.max(MIN_HEIGHT, Math.round(fittedHeight)),
  };
};

/**
 * Chooses the Canvas display footprint for a generated image.
 * The generated bytes may remain high resolution; only the local placement
 * size is normalized so Codex cannot create a visually oversized Asset.
 */
export function generatedAssetDisplaySize(
  state: CanvasState,
  referenceIds: EntityId[],
  requestedWidth = DEFAULT_ASSET_SIZE.width,
  requestedHeight = DEFAULT_ASSET_SIZE.height,
): GeneratedAssetDisplaySize {
  const safeWidth = Number.isFinite(requestedWidth) && requestedWidth > 0 ? requestedWidth : DEFAULT_ASSET_SIZE.width;
  const safeHeight = Number.isFinite(requestedHeight) && requestedHeight > 0 ? requestedHeight : DEFAULT_ASSET_SIZE.height;
  const aspectRatio = safeWidth / safeHeight;
  const references = state.assets.filter((asset) => referenceIds.includes(asset.id));

  if (references.length === 0) return fitWithin(MAX_FALLBACK_WIDTH, MAX_FALLBACK_HEIGHT, aspectRatio);

  const largestReferenceWidth = Math.max(...references.map((asset) => asset.width));
  const largestReferenceHeight = Math.max(...references.map((asset) => asset.height));
  return fitWithin(largestReferenceWidth, largestReferenceHeight, aspectRatio);
}
